FROM node:24.15.0-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration production --output-path dist/clinica-dental-frontend

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/clinica-dental-frontend/browser /usr/share/nginx/html

EXPOSE 80
